#define SECRET_SSID "CE-Hub-Student"
#define SECRET_PASS "casa-ce-gagarin-public-service"
#define SECRET_MQTTUSER "datasense@ttn"
#define SECRET_MQTTPASS "NNSXS.NHPXHJCKORY4WGEK2UDYXNETHH3RC2MGBTLKEDI.GJ3GL5LODBZB6UKXNCKFFC3GQM3S6ZPEP5G6QKALX53XLOMW76UA";